// Curated default hotel dining catalog. Used by HotelDiningPage to seed the
// menu with one click. Items are Indian-hotel staples — Indian + Chinese + a
// few universal sides — so a new hotel can have a real menu in seconds.
//
// Categories match the default seeds in StoreSettings.hotelMenuCategories.
// If a hotel edits that setting, both HotelDiningPage and HotelBilling will
// pick up the change automatically (see the single-source-of-truth wiring in
// hotelMenuCategories.js).

export const HOTEL_MENU_DEFAULT_CATEGORIES = [
  "Veg Menu",
  "Non Veg Menu",
  "Starter",
  "Chinese",
  "Desserts",
  "Beverages",
];

export const HOTEL_MENU_DEFAULT_CATALOG = [
  // Veg --------------------------------------------------------------
  {
    name: "Paneer Butter Masala",
    category: "Veg Menu",
    price: 280,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Kadhai Paneer",
    category: "Veg Menu",
    price: 290,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Dal Makhani",
    category: "Veg Menu",
    price: 220,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Dal Tadka",
    category: "Veg Menu",
    price: 200,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Veg Biryani",
    category: "Veg Menu",
    price: 240,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Shahi Paneer",
    category: "Veg Menu",
    price: 300,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Palak Paneer",
    category: "Veg Menu",
    price: 260,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Mix Veg",
    category: "Veg Menu",
    price: 200,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Aloo Gobi",
    category: "Veg Menu",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Mushroom Do Pyaza",
    category: "Veg Menu",
    price: 260,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },

  // Non-Veg ----------------------------------------------------------
  {
    name: "Butter Chicken",
    category: "Non Veg Menu",
    price: 320,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Chicken Biryani",
    category: "Non Veg Menu",
    price: 320,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Mutton Rogan Josh",
    category: "Non Veg Menu",
    price: 420,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "hot",
  },
  {
    name: "Chicken Curry",
    category: "Non Veg Menu",
    price: 280,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Kadhai Chicken",
    category: "Non Veg Menu",
    price: 310,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Egg Curry",
    category: "Non Veg Menu",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Chicken Tikka Masala",
    category: "Non Veg Menu",
    price: 340,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Tandoori Chicken (Half)",
    category: "Non Veg Menu",
    price: 320,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "hot",
  },
  {
    name: "Fish Curry",
    category: "Non Veg Menu",
    price: 360,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },

  // Starter ----------------------------------------------------------
  {
    name: "Paneer Tikka",
    category: "Starter",
    price: 220,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Chicken Tikka",
    category: "Starter",
    price: 260,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "medium",
  },
  {
    name: "Veg Manchurian Dry",
    category: "Starter",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Veg Spring Roll",
    category: "Starter",
    price: 160,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Hara Bhara Kebab",
    category: "Starter",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Fish Amritsari",
    category: "Starter",
    price: 280,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "hot",
  },
  {
    name: "Crispy Corn",
    category: "Starter",
    price: 160,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Chilli Paneer Dry",
    category: "Starter",
    price: 220,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "hot",
  },

  // Chinese ----------------------------------------------------------
  {
    name: "Veg Fried Rice",
    category: "Chinese",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Chicken Fried Rice",
    category: "Chinese",
    price: 220,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "mild",
  },
  {
    name: "Veg Hakka Noodles",
    category: "Chinese",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Chicken Hakka Noodles",
    category: "Chinese",
    price: 220,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "mild",
  },
  {
    name: "Veg Manchurian Gravy",
    category: "Chinese",
    price: 200,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Chilli Chicken",
    category: "Chinese",
    price: 240,
    gst: 5,
    hsn: "9963",
    isVeg: false,
    spiceLevel: "hot",
  },
  {
    name: "Honey Chilli Potato",
    category: "Chinese",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "medium",
  },
  {
    name: "Schezwan Fried Rice",
    category: "Chinese",
    price: 200,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "hot",
  },

  // Desserts ---------------------------------------------------------
  {
    name: "Gulab Jamun (2 pcs)",
    category: "Desserts",
    price: 80,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Rasmalai",
    category: "Desserts",
    price: 120,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Ice Cream (Vanilla)",
    category: "Desserts",
    price: 90,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Gajar Halwa",
    category: "Desserts",
    price: 110,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Brownie with Ice Cream",
    category: "Desserts",
    price: 180,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },

  // Beverages --------------------------------------------------------
  {
    name: "Masala Chai",
    category: "Beverages",
    price: 40,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Filter Coffee",
    category: "Beverages",
    price: 50,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Fresh Lime Soda",
    category: "Beverages",
    price: 80,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Mango Lassi",
    category: "Beverages",
    price: 90,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Sweet Lassi",
    category: "Beverages",
    price: 70,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
  {
    name: "Mineral Water (1L)",
    category: "Beverages",
    price: 40,
    gst: 5,
    hsn: "9963",
    isVeg: true,
    spiceLevel: "mild",
  },
];

// Normalized lookup key so we never double-seed the same item into a store.
export const normalizeMenuName = (value) =>
  String(value || "")
    .trim()
    .toLowerCase();
